# Frontend Dockerfile
FROM node:14

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json /app/

# Install npm packages
RUN npm install

# Copy the rest of the frontend code
COPY . /app/

# Build the app
RUN npm run build

# Install serve to serve the build folder
RUN npm install -g serve

# Command to serve the app
CMD ["serve", "-s", "build", "-l", "3000"]
